#include<iostream>
#include<cmath>
#include<map>
#include<string>

// NOTE:
//  Get rid of std. we should start getting used to doing std:: 
//   std:: everything std::vector, std::map, std::yourmommaa
using namespace std;

// NOTE:
//  This is the perfect oppurutunity we can use OOP right here and group these functions under a struct
// This will avoid the duplication of this func call
// We can instead create like a coverter.h converter.cpp
//  Cool thing to learn later on: 
       in C++ there is somethign called the rule of 5
           The rule of 5 the compiler clang, gnu will generate 5 constructors by default unless you edit them
            **The 5 Constructors generated by the compiler below**
             Destructor ~Obj()             Ex: Destroys the object
             Copy Constructor              Ex: obj()
             Copy assignment Constructor   Ex: Obj = obj
             Move Constructor              Ex: Obj (std::move(Obj)) // Do not worry about std::move for right now
             Move Assignemnt Constructor   Ex: Obj = std::move(obj_ // Do not worry about std::move for right now
        below we are overriding the copy constructor
       Reason this is important to know is that sometimes in C++ you want to safeguard your object by certain operations not possible
         example: I do not want my object to be able to be copied because it is a very heavy object lets say is a 1mb. So I make it not copyable
              Obj (const Obj)=delete;                // Disable copy constructor
              Obj& operator=(const Obj&) = delete;   // Disable Copy assignment Constructor
// Example:
//    class Converter {
      private:
//      char   m_unit
//      char   m_convertedUnit
//      double m_value;
     public:
       Converter(char unit, char convertedUnit, double value)
        : m_unit { unit }
        , m_convertedUnit { convertedUnit } 
        , m_value { value }
        {}

       [[nodiscard]] double convertlength()  const   noexcept;
       [[nodiscard]] double convertWeight()  const    noexcept;
       [[nodiscard]] double convertTemperature() const noexcept;
//      
//
// };

double convertlength(double, char , char );
double convertWeight(double , char , char );
double convertTemperature(double , char, char);


int main(){
    char unit;
    cout << "Select Unit you want to convert: (L for length, W for weight T for temperature)\n";
    cin >> unit;

    bool valid = (unit == 'L' || unit == 'W' || unit == 'T');
    if(!valid){
        cout << "Please enter a valid unit\n";
        return 1;

    }

    // NOTE:
    // Instead of instantiating a l_unit, l_coverted_unit, value per type category
    // We can instead just create a generic one above the conditional statements.
    // Reduces the repetition of l_unit, m_unit
    if(unit == 'L'){
        char L_unit;
        char L_converted_unit;
        double L_value;
        cout << "Please select current unit: \n";
        cout << "(M for Meters)  (K for Kilometers) (I for Inches) (m for miles)\n";
        cin >> L_unit;
        cout << "Please select value of your unit: \n";
        cin >> L_value;
        cout << "please select unit you would like to convert to: \n";
        cout << "(M for Meters)  (K for Kilometers) (I for Inches) (m for miles)\n";
        cin >> L_converted_unit;


        // NOTE:
        // if you move the following into a object then during the constructor you can validate that throw an error if user input is invalid
        bool L_valid = ((L_unit == 'M' || L_unit == 'K' || L_unit == 'I' || L_unit == 'm') && (L_converted_unit == 'M' || L_converted_unit == 'K' || L_converted_unit == 'I' || L_converted_unit == 'm'));
        if (!L_valid){
            cout << "Enter Valid unit for length\n";
            return 1;
        }

        if (L_unit == L_converted_unit){
            cout << "Please select a different unit to convert to:\n ";
            return 1;
        }

        double result = convertlength( L_value, L_unit, L_converted_unit);
        cout << "Your New Value is " << result <<  " " << L_converted_unit << "\n";
    }


    //For weight
    if(unit == 'W'){
        char W_unit;
        char W_converted_unit;
        double W_value;
        cout << "Please select current unit: \n";
        cout << "(G for Grams)  (K for Kilograms) (P for Pounds)\n";
        cin >> W_unit;
        cout << "Please select value of your unit: \n";
        cin >> W_value;
        cout << "please select unit you would like to convert to: \n";
        cout << "(G  for Grams)  (K for Kilograms) (P for Pounds)\n";
        cin >> W_converted_unit;

        bool W_valid = ((W_unit == 'G' || W_unit == 'K' || W_unit == 'P') && (W_converted_unit == 'G' || W_converted_unit == 'K' || W_converted_unit == 'P' ));
        if (!W_valid){
            cout << "Enter Valid unit for Weight\n";
            return 1;
        }
        double result =  convertWeight( W_value,  W_unit, W_converted_unit);
        cout << "Your New Value is " << result <<  " " << W_converted_unit << "\n";
    } 


    //For Temperature
    if(unit == 'T'){
        char T_unit;
        char T_converted_unit;
        double T_value;
        cout << "Please select current unit: \n";
        cout << "(C for Celsius)  (F for Fahrenheit) \n";
        cin >> T_unit;
        cout << "Please select value of your unit: \n";
        cin >> T_value;
        cout << "please select unit you would like to convert to: \n";
        cout << "(C for Celsius)  (F for Fahrenheit) \n";
        cin >> T_converted_unit;

        bool T_valid = ((T_unit == 'C' || T_unit == 'F' ) && (T_converted_unit == 'C' || T_converted_unit == 'F' ));
        if (!T_valid){
            cout << "Enter Valid unit for Temperature\n";
            return 1;
        }

        double result = convertTemperature(T_value, T_unit, T_converted_unit);
        cout << "Your New Value is " << result << " " << T_converted_unit << "\n";
}
    
}
double convertlength(double L_value, char L_unit, char L_converted_unit){
    // NOTE:
    //  Swap the map into a switch statement. The Map is pretty heavy to construct as it requires Heap memory. Rule of thumb in C++ try to keep everything on the stack
    //    unless you have no choice and have too use the heap. Use sparingly
    // Example of how you can swap
           switch(L_unit) {
           case 'M': return 1.0 break
           ...
           }
    // You can move it into a function in the object maybe call it Converter.LookUp()
    // This functiomn in the object will have a switch statement for all the letters like 'M' 'K' and your grams. This 
    // will be faster than using the map as the compiler can optimize the branches and it will be way faster than looking up through a map
           
     //Create a Map to store the values of conversions from the Unit Meter to all other units
        map<char, double> toMeter = {
            {'M', 1.0},
            {'K', 1000.0},
            {'I', 0.0254},
            {'m', 1609.347}
       
        };

         // create a variable meters to store the value converted to meters
        // NOTE: 
        // I like the use of .at() a lot safer than normal subscript[] andn will throw an exception
        double meters = L_value * toMeter.at(L_unit);
        //Return the value in the unit we are converting to
        return meters / toMeter.at(L_converted_unit);


}

double convertWeight(double W_value, char W_unit, char W_converted_unit){
    //Create a Map to store the values of conversions from the Unit Grams to all other units
    // NOTE: Check note above
    map<char, double> toGrams = {
        {'G', 1.0},
        {'K', 1000.0},
        {'P', 453.6}
        
    

    };
    // create a variable grams to store the value converted to Grams
    double grams = W_value * toGrams.at(W_unit);
    //Return the value in the unit we are converting to
    return grams / toGrams.at(W_converted_unit);
}



double convertTemperature(double T_value, char T_unit, char T_converted_unit){
    //For Celsius unit selection

    if (T_unit == 'C' && T_converted_unit == 'F'){
        return (9.0/5.0 * T_value) + 32;

    }
    

    //fOR Fahrenheit 
    if (T_unit == 'F' && T_converted_unit == 'C'){
        return (5.0/9.0) * (T_value - 32);
        
    }
}



       
        
